#!/usr/bin/env python3
"""
generate_lcr_templates.py
Run once to auto-generate engine/definitions/lcr_templates.py
from the EBA Annotated Table Layout Excel file.

Usage:
    python generate_lcr_templates.py

Requirements:
    pip install openpyxl
    
Place this script in the root of your eba-xbrl-engine project.
The Excel file must be in the same directory.
"""

import re, os, openpyxl

EXCEL_FILE = "20260106-Annotated-Table-Layout-COREP-4.2-COREP_LCR_DACOREP-4.2-7.xlsx"
OUTPUT_FILE = os.path.join("engine", "definitions", "lcr_templates.py")

FILING_INDICATORS = {
    "C_72.00.a": "eba_LCI:LI72",  "C_72.00.w": "eba_LCI:LI72",
    "C_73.00.a": "eba_LCI:LI73",  "C_73.00.w": "eba_LCI:LI73",
    "C_74.00.a": "eba_LCI:LI74",  "C_74.00.w": "eba_LCI:LI74",
    "C_75.01.a": "eba_LCI:LI75_1","C_75.01.w": "eba_LCI:LI75_1",
    "C_76.00.a": "eba_LCI:LI76",  "C_76.00.b": "eba_LCI:LI76",
    "C_76.00.w": "eba_LCI:LI76",  "C_76.00.y": "eba_LCI:LI76",
}
SHEET_CODES = {
    "C_72.00.a":"C 72.00","C_72.00.w":"C 72.00",
    "C_73.00.a":"C 73.00","C_73.00.w":"C 73.00",
    "C_74.00.a":"C 74.00","C_74.00.w":"C 74.00",
    "C_75.01.a":"C 75.01","C_75.01.w":"C 75.01",
    "C_76.00.a":"C 76.00","C_76.00.b":"C 76.00",
    "C_76.00.w":"C 76.00","C_76.00.y":"C 76.00",
}
TEMPLATE_NAMES = {
    "C_72.00.a":"Liquid Assets - Total",
    "C_72.00.w":"Liquid Assets - Significant currencies",
    "C_73.00.a":"Liquidity Outflows - Total",
    "C_73.00.w":"Liquidity Outflows - Significant currencies",
    "C_74.00.a":"Liquidity Inflows - Total",
    "C_74.00.w":"Liquidity Inflows - Significant currencies",
    "C_75.01.a":"Collateral Swaps - Total",
    "C_75.01.w":"Collateral Swaps - Significant currencies",
    "C_76.00.a":"LCR Calculations - Total (a)",
    "C_76.00.b":"LCR Calculations - Total (b)",
    "C_76.00.w":"LCR Calculations - Significant currencies (w)",
    "C_76.00.y":"LCR Calculations - Significant currencies (y)",
}


def extract_vid(cell_value):
    if cell_value is None:
        return None
    m = re.match(r"^(\d+)", str(cell_value).strip())
    return int(m.group(1)) if m else None


def parse_sheet(wb, sheet_name):
    ws = wb[sheet_name]
    rows_data = list(ws.iter_rows(values_only=True))
    col_map, col_code_row_idx = {}, None

    for i, row in enumerate(rows_data):
        valid = [(j, str(v)) for j, v in enumerate(row)
                 if v and re.match(r"^\d{4}$", str(v)) and j >= 3]
        if valid:
            col_code_row_idx = i
            label_row = rows_data[i - 1] if i > 0 else [None] * len(row)
            for j, code in valid:
                lbl = label_row[j] if j < len(label_row) else None
                col_map[code] = (j + 1, str(lbl)[:60].replace('"', "'") if lbl else f"col_{code}")
            break

    if col_code_row_idx is None:
        return {}, {}, {}

    row_map, cell_map = {}, {}
    for i in range(col_code_row_idx + 1, len(rows_data)):
        row = rows_data[i]
        if not any(v is not None for v in row):
            continue
        rc_val = row[2] if len(row) > 2 else None
        if not rc_val or not re.match(r"^\d{4}$", str(rc_val)):
            continue
        rcode = str(rc_val)
        lbl = str(row[1]).strip()[:80].replace('"', "'") if row[1] else f"r{rcode}"
        row_map[rcode] = (i + 1, lbl)
        for ccode, (cexcel, _) in col_map.items():
            j = cexcel - 1
            if j < len(row):
                vid = extract_vid(row[j])
                if vid:
                    cell_map[(rcode, ccode)] = vid

    return col_map, row_map, cell_map


def main():
    if not os.path.exists(EXCEL_FILE):
        print(f"ERROR: {EXCEL_FILE} not found.")
        print("Place the EBA Annotated Table Layout Excel file in this directory.")
        return

    print(f"Reading {EXCEL_FILE} ...")
    wb = openpyxl.load_workbook(EXCEL_FILE, read_only=True)
    target_sheets = [s for s in wb.sheetnames if s not in ("TOC", "C_00.01", "C_77.00")]

    lines = [
        '"""',
        "engine/definitions/lcr_templates.py",
        "LCR Delegated Act (DA 2015/61) — COREP 4.2",
        "Auto-generated by generate_lcr_templates.py",
        "Variable IDs extracted from EBA Annotated Table Layout 20260106",
        '"""',
        "",
        "LCR_TEMPLATES = {",
    ]

    total_concepts = 0
    for sname in target_sheets:
        col_map, row_map, cell_map = parse_sheet(wb, sname)
        total_concepts += len(cell_map)
        print(f"  {sname:20s}  cols={len(col_map):2d}  rows={len(row_map):3d}  cells={len(cell_map):4d}")

        lines.append(f'    "{sname}": {{')
        lines.append(f'        "template_code":         "{SHEET_CODES.get(sname, sname)}",')
        lines.append(f'        "name":                  "{TEMPLATE_NAMES.get(sname, sname)}",')
        lines.append(f'        "xbrl_filing_indicator": "{FILING_INDICATORS.get(sname, "")}",')
        lines.append(f'        "is_ccy_sheet":           {str(sname.endswith(".w") or sname.endswith(".y"))},')

        lines.append('        "columns": {')
        for ccode, (excol, lbl) in sorted(col_map.items()):
            lines.append(f'            "{ccode}": {{"label": "{lbl}", "excel_col": {excol}}},')
        lines.append('        },')

        lines.append('        "rows": {')
        for rcode, (exrow, lbl) in sorted(row_map.items()):
            lines.append(f'            "{rcode}": {{"label": "{lbl}", "excel_row": {exrow}}},')
        lines.append('        },')

        lines.append('        "cell_map": {')
        for (rcode, ccode), vid in sorted(cell_map.items()):
            lines.append(f'            ("{rcode}", "{ccode}"): "eba_met:mi{vid}",')
        lines.append('        },')
        lines.append('    },')

    lines.append("}")
    lines.append("")

    wb.close()

    content = "\n".join(lines)
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"\n✅ Generated {OUTPUT_FILE}")
    print(f"   Sheets:   {len(target_sheets)}")
    print(f"   Concepts: {total_concepts:,} (eba_met:mi{{id}} format)")
    print(f"   Size:     {len(content):,} chars")


if __name__ == "__main__":
    main()
