
LCR_TEMPLATES = {
    "C_72_00": {
        "template_code": "C 72.00", "name": "Liquid Assets",
        "sheet_name": "C 72.00", "xbrl_filing_indicator": "eba_LCI:LI72",
        "rows": {
            "r0020": {"label": "Coins and banknotes",                       "excel_row": 9},
            "r0030": {"label": "Withdrawable central bank reserves",        "excel_row": 10},
            "r0040": {"label": "Central bank assets",                       "excel_row": 11},
            "r0050": {"label": "Centr. gov / centr. bank assets (L1)",      "excel_row": 12},
            "r0060": {"label": "Reg. gov / PSE assets (L1)",                "excel_row": 13},
            "r0070": {"label": "Third country assets (L1)",                 "excel_row": 14},
            "r0080": {"label": "Extremely HQ covered bonds",                "excel_row": 15},
            "r0090": {"label": "CIU shares/units (L1)",                     "excel_row": 16},
            "r0100": {"label": "Other Level 1 assets",                      "excel_row": 17},
            "r0120": {"label": "Centr. gov / centr. bank assets (L2A)",     "excel_row": 19},
            "r0130": {"label": "Reg. gov / PSE / MDB / IO assets (L2A)",   "excel_row": 20},
            "r0140": {"label": "High quality covered bonds (L2A)",          "excel_row": 21},
            "r0150": {"label": "Corporate debt securities (L2A)",           "excel_row": 22},
            "r0160": {"label": "CIU shares/units (L2A)",                    "excel_row": 23},
            "r0180": {"label": "ABS residential or auto (L2B)",             "excel_row": 25},
            "r0190": {"label": "ABS auto (L2B)",                            "excel_row": 26},
            "r0200": {"label": "HQ covered bonds (L2B)",                    "excel_row": 27},
            "r0210": {"label": "Corporate debt securities (L2B)",           "excel_row": 28},
            "r0220": {"label": "Equities (L2B)",                            "excel_row": 29},
            "r0230": {"label": "CIU shares/units (L2B)",                    "excel_row": 30},
            "r0310": {"label": "TOTAL LIQUID ASSETS",                       "excel_row": 31},
        },
        "columns": {
            "c0010": {"label": "Market Value",              "excel_col": 3},
            "c0020": {"label": "Applicable haircut",        "excel_col": 4},
            "c0030": {"label": "Value after haircut",       "excel_col": 5},
            "c0040": {"label": "Value applicable under cap","excel_col": 6},
        }
    },
    "C_73_00": {
        "template_code": "C 73.00", "name": "Liquidity Coverage - Outflows",
        "sheet_name": "C 73.00", "xbrl_filing_indicator": "eba_LCI:LI73",
        "rows": {
            "r0010": {"label": "Retail deposits and deposits from SMEs",    "excel_row": 8},
            "r0020": {"label": "Stable deposits",                           "excel_row": 9},
            "r0030": {"label": "Less stable deposits",                      "excel_row": 10},
            "r0040": {"label": "Deposits subject to higher outflows",       "excel_row": 11},
            "r0050": {"label": "Operational deposits",                      "excel_row": 12},
            "r0060": {"label": "Non-operational deposits",                  "excel_row": 13},
            "r0070": {"label": "Unsecured wholesale funding",               "excel_row": 14},
            "r0080": {"label": "Secured funding",                           "excel_row": 15},
            "r0090": {"label": "Additional requirements",                   "excel_row": 16},
            "r0100": {"label": "Outflows from credit/liquidity facilities", "excel_row": 17},
            "r0110": {"label": "Other outflows",                            "excel_row": 18},
            "r0200": {"label": "TOTAL OUTFLOWS",                            "excel_row": 19},
        },
        "columns": {
            "c0010": {"label": "Outstanding balance / notional", "excel_col": 3},
            "c0020": {"label": "Outflow rate (%)",               "excel_col": 4},
            "c0030": {"label": "Outflows",                       "excel_col": 5},
        }
    },
    "C_74_00": {
        "template_code": "C 74.00", "name": "Liquidity Coverage - Inflows",
        "sheet_name": "C 74.00", "xbrl_filing_indicator": "eba_LCI:LI74",
        "rows": {
            "r0010": {"label": "Secured lending and capital market txns",   "excel_row": 8},
            "r0020": {"label": "Collateralised with L1 assets",             "excel_row": 9},
            "r0030": {"label": "Collateralised with L2A assets",            "excel_row": 10},
            "r0040": {"label": "Collateralised with L2B assets",            "excel_row": 11},
            "r0050": {"label": "Unsecured inflows from financial customers","excel_row": 12},
            "r0060": {"label": "Inflows from retail customers",             "excel_row": 13},
            "r0070": {"label": "Inflows from non-financial corporates",     "excel_row": 14},
            "r0080": {"label": "Inflows from central banks / fin. cust.",   "excel_row": 15},
            "r0090": {"label": "Operational deposits",                      "excel_row": 16},
            "r0100": {"label": "Other inflows",                             "excel_row": 17},
            "r0200": {"label": "TOTAL INFLOWS",                             "excel_row": 18},
        },
        "columns": {
            "c0010": {"label": "Outstanding amount", "excel_col": 3},
            "c0020": {"label": "Inflow rate (%)",    "excel_col": 4},
            "c0030": {"label": "Inflows",            "excel_col": 5},
        }
    },
    "C_75_00": {
        "template_code": "C 75.00", "name": "Liquidity Coverage - Collateral Swaps",
        "sheet_name": "C 75.00", "xbrl_filing_indicator": "eba_LCI:LI75",
        "rows": {
            "r0010": {"label": "Outright sale of liquid assets as collateral", "excel_row": 8},
            "r0020": {"label": "L1 exchanged for L1",          "excel_row": 9},
            "r0030": {"label": "L1 exchanged for L2A",         "excel_row": 10},
            "r0040": {"label": "L1 exchanged for L2B",         "excel_row": 11},
            "r0050": {"label": "L1 exchanged for non-HQLA",    "excel_row": 12},
            "r0060": {"label": "L2A exchanged for L1",         "excel_row": 13},
            "r0070": {"label": "L2A exchanged for L2A",        "excel_row": 14},
            "r0080": {"label": "L2A exchanged for L2B",        "excel_row": 15},
            "r0090": {"label": "L2A exchanged for non-HQLA",   "excel_row": 16},
            "r0100": {"label": "L2B exchanged for L1",         "excel_row": 17},
            "r0110": {"label": "L2B exchanged for L2A",        "excel_row": 18},
            "r0120": {"label": "L2B exchanged for L2B",        "excel_row": 19},
            "r0130": {"label": "L2B exchanged for non-HQLA",   "excel_row": 20},
            "r0140": {"label": "Non-HQLA exchanged for L1",    "excel_row": 21},
            "r0150": {"label": "Non-HQLA exchanged for L2A",   "excel_row": 22},
            "r0160": {"label": "Non-HQLA exchanged for L2B",   "excel_row": 23},
        },
        "columns": {
            "c0010": {"label": "Collateral received - market value", "excel_col": 3},
            "c0020": {"label": "Collateral posted - market value",   "excel_col": 4},
            "c0030": {"label": "Net impact on liquid assets buffer",  "excel_col": 5},
        }
    },
    "C_76_00": {
        "template_code": "C 76.00", "name": "LCR Calculation",
        "sheet_name": "C 76.00", "xbrl_filing_indicator": "eba_LCI:LI76",
        "rows": {
            "r0010": {"label": "Liquidity buffer",              "excel_row": 8},
            "r0020": {"label": "Total net liquidity outflows",  "excel_row": 9},
            "r0030": {"label": "Total outflows",                "excel_row": 10},
            "r0040": {"label": "Inflows from secured lending",  "excel_row": 11},
            "r0050": {"label": "Total inflows",                 "excel_row": 12},
            "r0060": {"label": "Fully exempt inflows",          "excel_row": 13},
            "r0070": {"label": "Inflows subject to 90% cap",   "excel_row": 14},
            "r0080": {"label": "Inflows subject to 75% cap",   "excel_row": 15},
            "r0090": {"label": "LCR (%)",                       "excel_row": 16},
        },
        "columns": {
            "c0010": {"label": "Value", "excel_col": 3},
        }
    }
}
